# Generated by Django 5.1.1 on 2024-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок рецепта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipies/photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Контекст главной страницы', 'verbose_name_plural': 'Контекст главной страницы'},
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
