# Generated by Django 5.1.1 on 2024-09-30 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipies_alter_posts_options_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата комментария'),
            preserve_default=False,
        ),
    ]
