# Generated by Django 5.1.1 on 2024-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comments_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
    ]
