# Generated by Django 5.1.1 on 2024-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='measurement',
            field=models.CharField(choices=[('кг', 'кг'), ('шт', 'шт')], default='кг', max_length=2),
        ),
    ]
